### PR TITLE
Add test for 3 millisecond font compositing

### PR DESCRIPTION
**Pull request by jakepruitt**
Added test to ensure that three protocol buffers can be composited in under 3 milliseconds.

Since compositing is done synchronously, 10 simultaneous calls to `glyphComposite.combine` will result in a total of 30 milliseconds of blocking time on the CPU.

@yhahn - I am not sure what is needed here. From what I can tell, protocol-buffer encoding/decoding is [very fast](https://github.com/mafintosh/protocol-buffers#performance), and we can't speed up the [computationally intensive](https://github.com/mapbox/glyph-pbf-composite/blob/master/index.js#L28-L48) process of compositing the coverage, unless we can find a way to avoid [sorting the 256 glyphs](https://github.com/mapbox/glyph-pbf-composite/blob/master/index.js#L48), or offload the compositing to workers/sub-processes.

### CODE REVIEW

**Comment by yhahn** [comment]
@jakepruitt :+1: agreed, your test to demonstrate the speed here looks good.

The only other quick optimization I can see around this atm would be switching from `.forEach()` to straight for loops.

**Comment by mikemorris** [comment]
If you're testing performance, maybe check out https://github.com/mapbox/pbf too, @mourner promised it was fast.

**Comment by jfirebaugh** [comment]
I recommend you add a benchmark for this but not an automated test. This test has a high probability of flapping because it happens to run while the system is loaded, or on a slower VM, or what have you.

**Comment by jakepruitt** [comment]
@jfirebaugh does this look better? The result of running the benchmark is:

```
<Test #1> x 1,668 ops/sec ±0.93% (94 runs sampled)
```

**Comment by jfirebaugh** [comment]
:+1:

**Pull request merged**
